export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,

  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  PAYLOAD_TOO_LARGE: 413,
  TOO_MANY_REQUESTS: 429,

  INTERNAL_SERVER_ERROR: 500,
  SERVICE_UNAVAILABLE: 503,
} as const;

export type HttpStatus = (typeof HTTP_STATUS)[keyof typeof HTTP_STATUS];

export const ERROR_CODES = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",

  USER_NOT_FOUND: "USER_NOT_FOUND",
  CHAT_NOT_FOUND: "CHAT_NOT_FOUND",
  GROUP_MAX_SIZE: "GROUP_MAX_SIZE",
  MESSAGE_NOT_FOUND: "MESSAGE_NOT_FOUND",
  ATTACHMENT_NOT_FOUND: "ATTACHMENT_NOT_FOUND",
  FILE_TOO_LARGE: "FILE_TOO_LARGE",
  STORAGE_QUOTA_EXCEEDED: "STORAGE_QUOTA_EXCEEDED",
  UNSUPPORTED_MEDIA_TYPE: "UNSUPPORTED_MEDIA_TYPE",
  FRIEND_REQUEST_NOT_FOUND: "FRIEND_REQUEST_NOT_FOUND",
  FRIENDSHIP_NOT_FOUND: "FRIENDSHIP_NOT_FOUND",
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",

  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  ACCOUNT_LOCKED: "ACCOUNT_LOCKED",

  USERNAME_ALREADY_EXISTS: "USERNAME_ALREADY_EXISTS",
  USERNAME_CHANGE_COOLDOWN: "USERNAME_CHANGE_COOLDOWN",
  ACCOUNT_ALREADY_EXISTS: "ACCOUNT_ALREADY_EXISTS",

  EMAIL_NOT_VERIFIED: "EMAIL_NOT_VERIFIED",

  INVALID_OR_EXPIRED_VERIFICATION_TOKEN:
    "INVALID_OR_EXPIRED_VERIFICATION_TOKEN",

  INVALID_OR_EXPIRED_RESET_TOKEN: "INVALID_OR_EXPIRED_RESET_TOKEN",
  INVALID_OR_EXPIRED_RECOVERY_TOKEN: "INVALID_OR_EXPIRED_RECOVERY_TOKEN",

  TWO_FACTOR_CODE_REQUIRED: "TWO_FACTOR_CODE_REQUIRED",
  INVALID_OR_EXPIRED_2FA_CODE: "INVALID_OR_EXPIRED_2FA_CODE",
  TWO_FACTOR_LOCKED: "TWO_FACTOR_LOCKED",

  INVALID_REFRESH_TOKEN: "INVALID_REFRESH_TOKEN",
  REFRESH_TOKEN_EXPIRED: "REFRESH_TOKEN_EXPIRED",
  REFRESH_TOKEN_REUSE_DETECTED: "REFRESH_TOKEN_REUSE_DETECTED",
  REFRESH_TOKEN_ROTATED: "REFRESH_TOKEN_ROTATED",

  PAYLOAD_TOO_LARGE: "PAYLOAD_TOO_LARGE",
  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",

  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  INVALID_API_RESPONSE: "INVALID_API_RESPONSE",
  BAD_REQUEST: "BAD_REQUEST",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export class AppError extends Error {
  requestId?: string;

  constructor(
    public readonly statusCode: HttpStatus,
    public readonly code: ErrorCode,
    message: string,
    public readonly details?: unknown,
  ) {
    super(message);

    this.name = "AppError";
  }
}
