export const HTTP_STATUS = {
	OK: 200,
	CREATED: 201,
	NO_CONTENT: 204,

	BAD_REQUEST: 400,
	UNAUTHORIZED: 401,
	FORBIDDEN: 403,
	NOT_FOUND: 404,
	CONFLICT: 409,
	TOO_MANY_REQUESTS: 429,

	INTERNAL_SERVER_ERROR: 500,
};

export const ERROR_CODES = {
	VALIDATION_ERROR: "VALIDATION_ERROR",
	UNAUTHORIZED: "UNAUTHORIZED",
	FORBIDDEN: "FORBIDDEN",

	USER_ID_NOT_VALID: "USER_ID_NOT_VALID",

	USER_NOT_FOUND: "USER_NOT_FOUND",
	CHAT_NOT_FOUND: "CHAT_NOT_FOUND",
	MESSAGE_NOT_FOUND: "MESSAGE_NOT_FOUND",
	ATTACHMENT_NOT_FOUND: "ATTACHMENT_NOT_FOUND",
	FILE_TOO_LARGE: "FILE_TOO_LARGE",
	UNSUPPORTED_MEDIA_TYPE: "UNSUPPORTED_MEDIA_TYPE",
	FRIEND_REQUEST_NOT_FOUND: "FRIEND_REQUEST_NOT_FOUND",
	FRIENDSHIP_NOT_FOUND: "FRIENDSHIP_NOT_FOUND",
	NOT_FOUND: "NOT_FOUND",
	CONFLICT: "CONFLICT",

	INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
	ACCOUNT_LOCKED: "ACCOUNT_LOCKED",

	EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
	USERNAME_ALREADY_EXISTS: "USERNAME_ALREADY_EXISTS",
	ACCOUNT_ALREADY_EXISTS: "ACCOUNT_ALREADY_EXISTS",

	EMAIL_NOT_VERIFIED: "EMAIL_NOT_VERIFIED",

	INVALID_OR_EXPIRED_VERIFICATION_TOKEN:
		"INVALID_OR_EXPIRED_VERIFICATION_TOKEN",

	INVALID_OR_EXPIRED_RESET_TOKEN: "INVALID_OR_EXPIRED_RESET_TOKEN",

	TWO_FACTOR_REQUIRED: "TWO_FACTOR_REQUIRED",
	INVALID_OR_EXPIRED_2FA_CODE: "INVALID_OR_EXPIRED_2FA_CODE",
	TWO_FACTOR_LOCKED: "TWO_FACTOR_LOCKED",

	INVALID_REFRESH_TOKEN: "INVALID_REFRESH_TOKEN",
	REFRESH_TOKEN_EXPIRED: "REFRESH_TOKEN_EXPIRED",

	INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
	INVALID_API_RESPONSE: "INVALID_API_RESPONSE",
	BAD_REQUEST: "BAD_REQUEST",
};

export class AppError extends Error {
	constructor(
		public readonly statusCode: number,
		public readonly code: string,
		message: string,
		public readonly details?: unknown,
	) {
		super(message);

		this.name = "AppError";
	}
}
