export const HTTP_STATUS = {
	OK: 200,
	CREATED: 201,
	NO_CONTENT: 204,

	BAD_REQUEST: 400,
	UNAUTHORIZED: 401,
	FORBIDDEN: 403,
	NOT_FOUND: 404,
	CONFLICT: 409,

	INTERNAL_SERVER_ERROR: 500,
};

export const ERROR_CODES = {
	VALIDATION_ERROR: "VALIDATION_ERROR",
	UNAUTHORIZED: "UNAUTHORIZED",
	FORBIDDEN: "FORBIDDEN",

	USER_ID_NOT_VALID: "USER_ID_NOT_VALID",

	USER_NOT_FOUND: "USER_NOT_FOUND",
	CHAT_NOT_FOUND: "CHAT_NOT_FOUND",
	MESSAGE_NOT_FOUND: "MESSAGE_NOT_FOUND",
	FRIEND_REQUEST_NOT_FOUND: "FRIEND_REQUEST_NOT_FOUND",
	FRIENDSHIP_NOT_FOUND: "FRIENDSHIP_NOT_FOUND",
	CONFLICT: "CONFLICT",

	INVALID_CREDENTIALS: "INVALID_CREDENTIALS",

	EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
	USERNAME_ALREADY_EXISTS: "USERNAME_ALREADY_EXISTS",
	ACCOUNT_ALREADY_EXISTS: "ACCOUNT_ALREADY_EXISTS",

	EMAIL_NOT_VERIFIED: "EMAIL_NOT_VERIFIED",

	INVALID_OR_EXPIRED_VERIFICATION_TOKEN:
		"INVALID_OR_EXPIRED_VERIFICATION_TOKEN",

	INVALID_OR_EXPIRED_RESET_TOKEN: "INVALID_OR_EXPIRED_RESET_TOKEN",

	INVALID_REFRESH_TOKEN: "INVALID_REFRESH_TOKEN",
	REFRESH_TOKEN_EXPIRED: "REFRESH_TOKEN_EXPIRED",

	INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
	INVALID_API_RESPONSE: "INVALID_API_RESPONSE0",
};

export class AppError extends Error {
	constructor(
		public readonly statusCode: number,
		public readonly code: string,
		message: string,
	) {
		super(message);

		this.name = "AppError";
	}
}
